# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-08 11:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docname', models.CharField(max_length=200)),
                ('readstatus', models.CharField(max_length=50)),
                ('docurl', models.CharField(max_length=300)),
                ('readlog', models.CharField(max_length=300)),
                ('usernote', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='SortTree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='docs',
            name='treenode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.SortTree'),
        ),
    ]
