# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-09 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20161208_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='sorttree',
            name='pathvalue',
            field=models.CharField(default='-', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sorttree',
            name='value',
            field=models.CharField(default='-', max_length=300),
            preserve_default=False,
        ),
    ]
