# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20161209_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docs',
            name='readlog',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='docs',
            name='usernote',
            field=models.TextField(),
        ),
    ]
