# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_docs_docfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docs',
            name='docfile',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
